apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
      - image: hashicorp/http-echo
        name: blue-app-container
        args: ["-listen=:8080", '-text="I am blue"']
