apiVersion: v1
kind: Service
metadata:
  name: green-app-svc
spec:
  selector:
    app: green-app
  ports:
  - name: green-app-port
    targetPort: 8081
    port: 8081
    protocol: TCP
  type: ClusterIP